#
# Configuration file to load the data for the ITS2 pid study
#

# enabling configuration
visualize: True

# Particle species
species: [ 'Unidentified', 'El',
          'Pi', 'Ka', 'Pr', 
          'De', 'He'
          ]

# Selections tags 
# It will be reqruired: 'nSigma{part name}Abs < selfSel and nSigma{part1}Abs > part1Sel  and nSigma{part2}Abs > part2Sel and p <= pmax',
selTags:  { #E: {selfSel: 2, part1: 'Pi', part1Sel: -1, part2: 'Pi', part2Sel: -1, pmax: 1.},
            Pi: {selfSel: 2, part1: 'E', part1Sel: 3, part2: 'K', part2Sel: 3, pmax: 1.},
            K: {selfSel: 2, part1: 'Pi', part1Sel: 3, part2: 'P', part2Sel: 3, pmax: 1.},
            P: {selfSel: 2, part1: 'K', part1Sel: 3, part2: 'Deu', part2Sel: 3, pmax: 1.},
            #Deu: {selfSel: 2, part1: 'P', part1Sel: -1, part2: 'P', part2Sel: -1, pmax: 1.}
          }

cuts:     { nClusTPCmin: 80,
            chi2ITSTPCmax: 6,
            etamax: 0.5
          }

nn_mode: 'classification' # 'classification' or 'regression'
features: ['fItsClusterSizeL0', 'fItsClusterSizeL1', 'fItsClusterSizeL2', 'fItsClusterSizeL3', 'fItsClusterSizeL4', 'fItsClusterSizeL5', 'fItsClusterSizeL6', 'fEta', 'fPhi', 'fCosL', 'fP', 'fMeanItsClSize', 'fClSizeCosL']
#features: ['fItsClusterSizeL0', 'fItsClusterSizeL1', 'fItsClusterSizeL2', 'fItsClusterSizeL3', 'fItsClusterSizeL4', 'fItsClusterSizeL5', 'fItsClusterSizeL6', 'fEta', 'fPhi', 'fCosL', 'fP']
target: 'fPartID'
oneHot: False
useClasses: True
oversample: True

num_threads: 1
num_epochs: 50
learning_rate: 0.01
batch_size: 32
test_size: 0.2
validation_size: 0.05

# data preparation 
